version: '2'
services:
  anonymous-slack:
    build:
      context: './'
    image: 'ioet/anonymous-slack'
    environment:
      - SLACK_SIGNING_SECRET=
      - TOKEN_BOT=
      - TOKEN_USER=
      - TIMEOUT_CONVERSATION=600000
      - BOT_ID=
      - USER_ADMIN=
    container_name: anonymous-slack
    ports:
      - 5000:5000
    restart: always
